// Code generated by ent, DO NOT EDIT.

package react

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the react type in the database.
	Label = "react"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldReactType holds the string denoting the react_type field in the database.
	FieldReactType = "react_type"
	// FieldPostType holds the string denoting the post_type field in the database.
	FieldPostType = "post_type"
	// EdgePosts holds the string denoting the posts edge name in mutations.
	EdgePosts = "posts"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeReactedUser holds the string denoting the reacted_user edge name in mutations.
	EdgeReactedUser = "reacted_user"
	// Table holds the table name of the react in the database.
	Table = "reacts"
	// PostsTable is the table that holds the posts relation/edge. The primary key declared below.
	PostsTable = "post_reacts"
	// PostsInverseTable is the table name for the Post entity.
	// It exists in this package in order to avoid circular dependency with the "post" package.
	PostsInverseTable = "posts"
	// CommentsTable is the table that holds the comments relation/edge. The primary key declared below.
	CommentsTable = "comment_reacts"
	// CommentsInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	CommentsInverseTable = "comments"
	// ReactedUserTable is the table that holds the reacted_user relation/edge. The primary key declared below.
	ReactedUserTable = "comment_reacts"
	// ReactedUserInverseTable is the table name for the Comment entity.
	// It exists in this package in order to avoid circular dependency with the "comment" package.
	ReactedUserInverseTable = "comments"
)

// Columns holds all SQL columns for react fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldReactType,
	FieldPostType,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "reacts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_reacted_user",
}

var (
	// PostsPrimaryKey and PostsColumn2 are the table columns denoting the
	// primary key for the posts relation (M2M).
	PostsPrimaryKey = []string{"post_id", "react_id"}
	// CommentsPrimaryKey and CommentsColumn2 are the table columns denoting the
	// primary key for the comments relation (M2M).
	CommentsPrimaryKey = []string{"comment_id", "react_id"}
	// ReactedUserPrimaryKey and ReactedUserColumn2 are the table columns denoting the
	// primary key for the reacted_user relation (M2M).
	ReactedUserPrimaryKey = []string{"comment_id", "react_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultReactType holds the default value on creation for the "react_type" field.
	DefaultReactType string
	// DefaultPostType holds the default value on creation for the "post_type" field.
	DefaultPostType string
)

// OrderOption defines the ordering options for the React queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByReactType orders the results by the react_type field.
func ByReactType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReactType, opts...).ToFunc()
}

// ByPostType orders the results by the post_type field.
func ByPostType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostType, opts...).ToFunc()
}

// ByPostsCount orders the results by posts count.
func ByPostsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPostsStep(), opts...)
	}
}

// ByPosts orders the results by posts terms.
func ByPosts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPostsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReactedUserCount orders the results by reacted_user count.
func ByReactedUserCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReactedUserStep(), opts...)
	}
}

// ByReactedUser orders the results by reacted_user terms.
func ByReactedUser(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReactedUserStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPostsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PostsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, PostsTable, PostsPrimaryKey...),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, CommentsTable, CommentsPrimaryKey...),
	)
}
func newReactedUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReactedUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, ReactedUserTable, ReactedUserPrimaryKey...),
	)
}
