// Code generated by ent, DO NOT EDIT.

package ent

import (
	"newsfeed/ent/attachment"
	"newsfeed/ent/comment"
	"newsfeed/ent/post"
	"newsfeed/ent/react"
	"newsfeed/ent/schema"
	"newsfeed/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	attachmentFields := schema.Attachment{}.Fields()
	_ = attachmentFields
	// attachmentDescPath is the schema descriptor for path field.
	attachmentDescPath := attachmentFields[0].Descriptor()
	// attachment.DefaultPath holds the default value on creation for the path field.
	attachment.DefaultPath = attachmentDescPath.Default.(string)
	// attachmentDescCreatedAt is the schema descriptor for created_at field.
	attachmentDescCreatedAt := attachmentFields[1].Descriptor()
	// attachment.DefaultCreatedAt holds the default value on creation for the created_at field.
	attachment.DefaultCreatedAt = attachmentDescCreatedAt.Default.(func() time.Time)
	// attachmentDescUpdatedAt is the schema descriptor for updated_at field.
	attachmentDescUpdatedAt := attachmentFields[2].Descriptor()
	// attachment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	attachment.DefaultUpdatedAt = attachmentDescUpdatedAt.Default.(func() time.Time)
	// attachment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	attachment.UpdateDefaultUpdatedAt = attachmentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// attachmentDescName is the schema descriptor for name field.
	attachmentDescName := attachmentFields[3].Descriptor()
	// attachment.DefaultName holds the default value on creation for the name field.
	attachment.DefaultName = attachmentDescName.Default.(string)
	commentFields := schema.Comment{}.Fields()
	_ = commentFields
	// commentDescCreatedAt is the schema descriptor for created_at field.
	commentDescCreatedAt := commentFields[0].Descriptor()
	// comment.DefaultCreatedAt holds the default value on creation for the created_at field.
	comment.DefaultCreatedAt = commentDescCreatedAt.Default.(func() time.Time)
	// commentDescUpdatedAt is the schema descriptor for updated_at field.
	commentDescUpdatedAt := commentFields[1].Descriptor()
	// comment.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	comment.DefaultUpdatedAt = commentDescUpdatedAt.Default.(func() time.Time)
	// comment.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	comment.UpdateDefaultUpdatedAt = commentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// commentDescContent is the schema descriptor for content field.
	commentDescContent := commentFields[2].Descriptor()
	// comment.DefaultContent holds the default value on creation for the content field.
	comment.DefaultContent = commentDescContent.Default.(string)
	// commentDescParentCommentID is the schema descriptor for parent_comment_id field.
	commentDescParentCommentID := commentFields[3].Descriptor()
	// comment.DefaultParentCommentID holds the default value on creation for the parent_comment_id field.
	comment.DefaultParentCommentID = commentDescParentCommentID.Default.(int)
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescCreatedAt is the schema descriptor for created_at field.
	postDescCreatedAt := postFields[0].Descriptor()
	// post.DefaultCreatedAt holds the default value on creation for the created_at field.
	post.DefaultCreatedAt = postDescCreatedAt.Default.(func() time.Time)
	// postDescUpdatedAt is the schema descriptor for updated_at field.
	postDescUpdatedAt := postFields[1].Descriptor()
	// post.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	post.DefaultUpdatedAt = postDescUpdatedAt.Default.(func() time.Time)
	// post.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	post.UpdateDefaultUpdatedAt = postDescUpdatedAt.UpdateDefault.(func() time.Time)
	// postDescContent is the schema descriptor for content field.
	postDescContent := postFields[2].Descriptor()
	// post.DefaultContent holds the default value on creation for the content field.
	post.DefaultContent = postDescContent.Default.(string)
	reactFields := schema.React{}.Fields()
	_ = reactFields
	// reactDescCreatedAt is the schema descriptor for created_at field.
	reactDescCreatedAt := reactFields[0].Descriptor()
	// react.DefaultCreatedAt holds the default value on creation for the created_at field.
	react.DefaultCreatedAt = reactDescCreatedAt.Default.(func() time.Time)
	// reactDescUpdatedAt is the schema descriptor for updated_at field.
	reactDescUpdatedAt := reactFields[1].Descriptor()
	// react.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	react.DefaultUpdatedAt = reactDescUpdatedAt.Default.(func() time.Time)
	// react.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	react.UpdateDefaultUpdatedAt = reactDescUpdatedAt.UpdateDefault.(func() time.Time)
	// reactDescReactType is the schema descriptor for react_type field.
	reactDescReactType := reactFields[2].Descriptor()
	// react.DefaultReactType holds the default value on creation for the react_type field.
	react.DefaultReactType = reactDescReactType.Default.(string)
	// reactDescPostType is the schema descriptor for post_type field.
	reactDescPostType := reactFields[3].Descriptor()
	// react.DefaultPostType holds the default value on creation for the post_type field.
	react.DefaultPostType = reactDescPostType.Default.(string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescName is the schema descriptor for name field.
	userDescName := userFields[0].Descriptor()
	// user.DefaultName holds the default value on creation for the name field.
	user.DefaultName = userDescName.Default.(string)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[1].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[2].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
