-- Create "users" table
CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("id"));
-- Create "comments" table
CREATE TABLE "comments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "content" character varying NULL DEFAULT '', "parent_comment_id" bigint NULL DEFAULT 0, "user_comments" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "comments_users_comments" FOREIGN KEY ("user_comments") REFERENCES "users" ("id") ON DELETE SET NULL);
-- Create "reacts" table
CREATE TABLE "reacts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "react_type" character varying NULL DEFAULT '', "post_type" character varying NULL DEFAULT '', "user_reacted_user" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "reacts_users_reacted_user" FOREIGN KEY ("user_reacted_user") REFERENCES "users" ("id") ON DELETE SET NULL);
-- Create "comment_reacts" table
CREATE TABLE "comment_reacts" ("comment_id" bigint NOT NULL, "react_id" bigint NOT NULL, PRIMARY KEY ("comment_id", "react_id"), CONSTRAINT "comment_reacts_comment_id" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON DELETE CASCADE, CONSTRAINT "comment_reacts_react_id" FOREIGN KEY ("react_id") REFERENCES "reacts" ("id") ON DELETE CASCADE);
-- Create "posts" table
CREATE TABLE "posts" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "content" character varying NULL DEFAULT '', PRIMARY KEY ("id"));
-- Create "attachments" table
CREATE TABLE "attachments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "path" character varying NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "name" character varying NULL DEFAULT '', "user_attachments" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "attachments_users_attachments" FOREIGN KEY ("user_attachments") REFERENCES "users" ("id") ON DELETE SET NULL);
-- Create "post_attachments" table
CREATE TABLE "post_attachments" ("post_id" bigint NOT NULL, "attachment_id" bigint NOT NULL, PRIMARY KEY ("post_id", "attachment_id"), CONSTRAINT "post_attachments_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE, CONSTRAINT "post_attachments_attachment_id" FOREIGN KEY ("attachment_id") REFERENCES "attachments" ("id") ON DELETE CASCADE);
-- Create "post_reacts" table
CREATE TABLE "post_reacts" ("post_id" bigint NOT NULL, "react_id" bigint NOT NULL, PRIMARY KEY ("post_id", "react_id"), CONSTRAINT "post_reacts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE, CONSTRAINT "post_reacts_react_id" FOREIGN KEY ("react_id") REFERENCES "reacts" ("id") ON DELETE CASCADE);
-- Create "user_posts" table
CREATE TABLE "user_posts" ("user_id" bigint NOT NULL, "post_id" bigint NOT NULL, PRIMARY KEY ("user_id", "post_id"), CONSTRAINT "user_posts_user_id" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE, CONSTRAINT "user_posts_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE);
-- Create "comment_attachments" table
CREATE TABLE "comment_attachments" ("comment_id" bigint NOT NULL, "attachment_id" bigint NOT NULL, PRIMARY KEY ("comment_id", "attachment_id"), CONSTRAINT "comment_attachments_comment_id" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON DELETE CASCADE, CONSTRAINT "comment_attachments_attachment_id" FOREIGN KEY ("attachment_id") REFERENCES "attachments" ("id") ON DELETE CASCADE);
-- Create "post_comments" table
CREATE TABLE "post_comments" ("post_id" bigint NOT NULL, "comment_id" bigint NOT NULL, PRIMARY KEY ("post_id", "comment_id"), CONSTRAINT "post_comments_post_id" FOREIGN KEY ("post_id") REFERENCES "posts" ("id") ON DELETE CASCADE, CONSTRAINT "post_comments_comment_id" FOREIGN KEY ("comment_id") REFERENCES "comments" ("id") ON DELETE CASCADE);
